### ISSUE TITLE
Latinamerican keyboard not recognized by word spelling

### ISSUE THREAD

**Issue by EJFuchs** [neosergio/Latam-Keyboard#1]
Hi. 

 I love your keyboard layout and use it on a daily basis.  I only have one issue: MSword.   MS Word has Spanish as the default language of a new document. When I start typing with your keyboard, everything looks fine until I type an accent (e.g., más). Then, Word stops recognizing the language and switches back to English for spelling. I have the option "recognize language" set to off.

**Comment by neosergio** [comment]
Have you tried to review, your shortcuts? It sounds like you have one activated to change language using those key combinations.

**Comment by EJFuchs** [comment]
No, I don't think the change language key combination is causing a problem. It is the accents, for some reason if you type any accent on any vowel, MSWord doesn't recognize it and switches back to English. This does not happen if you use the Spanish (from Spain) keyboard layout built in on Mac. With that one, the accents are recognized and the language setting on MS-Word remains in Spanish.  This only happens in MS-office, the native Mac apps work fine.  I have raised the question with MS as well.

**Comment by neosergio** [comment]
Please, can you make a video from your computer, to see what's going on, I have tried to replicate this bug with three different MacBooks, but I didn't have chances to do replicate it. The last try was just a minute ago using macOS Catalina 10.15.4  with MS Word Version 16.15 and accents are working fine with every vowel.

**Comment by neosergio** [comment]
I added a new kind of keyboard, please verify if error persists with new key layout.
