### ISSUE TITLE
Make icon white?

### ISSUE THREAD

**Issue by federicotdn** [neosergio/Latam-Keyboard#3]
On macOS Mojave, the Latin America continent icon is a bit hard to see against the dark (almost black) toolbar. All other icons next to the keyboard input are white (battery, wifi, etc.), so maybe we should change the icon to be white or light gray?

<img width="260" alt="Screenshot 2019-09-13 at 13 48 59" src="https://user-images.githubusercontent.com/6868935/64860394-4b7f0a00-d62d-11e9-80e0-6b270c682311.png">

**Comment by gmartinezkl** [comment]
Same problem here

**Comment by PREngineer** [comment]
I solved it by creating an .icns file from the attached file [here](https://cloudconvert.com) and then replacing the ones in the repo with it.

![latin](https://user-images.githubusercontent.com/6334069/74471081-9b2c6080-4e6d-11ea-8e91-a02e1c653994.png)

![Screen Shot 2020-02-13 at 2 35 41 PM](https://user-images.githubusercontent.com/6334069/74471415-2a397880-4e6e-11ea-8278-a7b87df6f8ef.png)

**Comment by federicotdn** [comment]
Thanks @PREngineer, that worked! I'll leave a .zip file here with both .icns files generated from your image
[Latam.zip](https://github.com/neosergio/Latam-Keyboard/files/4200878/Latam.zip)

**Comment by PREngineer** [comment]
@neosergio You can add the included files to the repository and close this issue.

**Comment by neosergio** [comment]
Thank you @federicotdn for your contribution. @PREngineer I will create two more keyboards with that white icon, I can't just replace the files because this is related to Light and Dark mode and is not related to Mojave

**Comment by neosergio** [comment]
It has been committed in https://github.com/neosergio/Latam-Keyboard/commit/ba2ea98b1fddb0e4d28965012b0d20ae70b55abf
