### ISSUE TITLE
Setear Latin American A a layout por default

### ISSUE THREAD

**Issue by josebarona** [neosergio/Latam-Keyboard#4]
Sera posible setear _Latin American A_ como layout por defecto?
Es el unico teclado que tengo, esta conectado a una pc con Mac OS mojave, no consigo escribir porque se regresa a inmediatamente a español

**Comment by federicotdn** [comment]
En "Input Sources", no podés borrar todos los ítems de la lista y dejar solo el de Latin American?

**Comment by josebarona** [comment]
no me deja selecionar por defecto latin America :c 
no puedo borrar todos y dejar latin American, siempre queda 1 extra, que no me aparece el icono de borrar :c

**Comment by federicotdn** [comment]
Mmm tenés razón, a mi tampoco me deja. Quizás te alcance con usar una combinación de teclas para cambiar de input source. Si ves que está puesta la que no querés entonces apretás esa combinación y la cambiás rápido.

**Comment by neosergio** [comment]
Gracias @josebarona y @federicotdn por participar en este repositorio, al parecer no es posible que quede como único teclado, ningún teclado custom como este. Es por eso que no pueden borrar todos y dejar solo los latinoamericanos.

Por otro lado probaste con dejar desactivado el check de cambio automático por idioma, porque me parece que eso es lo que falta, el documento se detecta como español y cambia a ese idioma, lo otro que puede resultar es en lugar de tener Español como idioma predeterminado, puedes tener Ingles Internacional como idioma predeterminado y así evitar el cambio automático.

![image](https://user-images.githubusercontent.com/50982/80978876-3fc69a80-8dec-11ea-9228-3b3b0b89cac7.png)
