### ISSUE TITLE
Cmd + + doesn't work on browsers

### ISSUE THREAD

**Issue by mig8447** [neosergio/Latam-Keyboard#6]
For some reason, the Cmd + + shortcut for zooming in doesn't work on Chromium browsers, when I use Latin American A, would you know if there's any way to make it work?

**Comment by PaoloLuciano** [comment]
Hi @neosergio! I've been using your amazing keyboard layout and I can't thank you enough! You're saving the whole international Latin community. Gracias!!

However, I have the same issue as @mig8447, for some reason the cmd + + is not working on any app for that matter. i.e. it's not sending the combination of keys. I really want to help but I'd lie if this goes beyond my expertize. Can you point me out to the right resources and I'd be happy to open a pull request

**Comment by VolodyaCO** [comment]
For me cmd + + works on vscode but not on browsers 🤔 

EDIT:
However, if use th num block + and - keys, I'm able to zoom in and out in a browser

**Comment by PaoloLuciano** [comment]
Hi @VolodyaCO I just replicated exactly what you describe :)

It's werid that it doesn't work on browers. Another place where it doesn't work is Excel (to add new rows) which unfortunately I'm forced to use for work haha

I'm sure that there's a combination of keys that's not being sent properly. I've dug a bit on the files and  it's just a matter of finding the right key code & output. Anyone knows which language is this? I'd like to fix it and open the pull request for @neosergio

**Comment by neosergio** [comment]
Hi @PaoloLuciano @VolodyaCO.
Thank you for using this project and for the positive feedback. Can you please give me more details about the macOS versions you are using? Perhaps it will need to remap or generate a new version for newer macOS. Also, what kind is your actual physical keyboard? External? Built-in English / Spanish version?

**Comment by neosergio** [comment]
After some search about possible issues, I found this: https://techcommunity.microsoft.com/t5/discussions/zoom-not-working-with-cmd-on-m1-mac/m-p/3055943, so it's possibly related to Chrome specifically @mig8447. @VolodyaCO I tried Safari and it is working properly.

**Comment by mig8447** [comment]
I thought I had posted this but I found that the issue is that the layout of the keyboard changes back to ABC when cmd is pressed (Or any modifier really), It is visible when you use the virtual keyboard

Normal:
![CleanShot 2023-08-03 at 12 25 52@2x](https://github.com/neosergio/Latam-Keyboard/assets/11009660/af4fa2fd-c4fe-4999-acf6-10dc9ca0e1ff)

With Cmd Pressed:
![CleanShot 2023-08-03 at 12 26 31@2x](https://github.com/neosergio/Latam-Keyboard/assets/11009660/c167812a-fde7-423d-ab00-0a937766cd6d)

**Comment by neosergio** [comment]
@PaoloLuciano I remap, a draft keyboard using + equivalence in charset: &#x002B; results are the same (https://www.w3.org/Style/XSL/TestSuite/results/4/XEP/charsets.pdf). So I think is not related to mapping, however, if you can find any error, feel free to send a PR with the fix. Language is XML

**Comment by neosergio** [comment]
> I thought I had posted this but I found that the issue is that the layout of the keyboard changes back to ABC when cmd is pressed (Or any modifier really), It is visible when you use the virtual keyboard
> 
> Normal: ![CleanShot 2023-08-03 at 12 25 52@2x](https://user-images.githubusercontent.com/11009660/258202260-af4fa2fd-c4fe-4999-acf6-10dc9ca0e1ff.png)
> 
> With Cmd Pressed: ![CleanShot 2023-08-03 at 12 26 31@2x](https://user-images.githubusercontent.com/11009660/258202267-c167812a-fde7-423d-ab00-0a937766cd6d.png)

Such a good finding. Thank you @mig8447

**Comment by PaoloLuciano** [comment]
What an amazing find @mig8447 ! Thanks for posting :)
I switched to an american keyboard layout and it works as intende (zooming in / inserting rows respectively). Hence, this is clearly the issue. 

Thanks also @neosergio for the suggestions. I'll try to figure out the mapping of what happens when you press the cmd key. I'm assuming it's a modifier

Gracias a todos :)

**Comment by mig8447** [comment]
@neosergio Is there any re-mapping that can be done when modifiers are pressed?, If that's the case, could you provide any pointers as how to contribute and make those changes if you don't have time?

I believe this is the most accurate layout out there. Not even the LA layout from Apple works with their own LA keyboards, the only issue is that is making me have workarounds in my computer is Cmd + + and Cmd + - (Using BetterTouchTool so that Cmd plus/minus presses the plus on the numpad instead)

**Comment by VolodyaCO** [comment]
> Hi @PaoloLuciano @VolodyaCO. Thank you for using this project and for the positive feedback. Can you please give me more details about the macOS versions you are using? Perhaps it will need to remap or generate a new version for newer macOS. Also, what kind is your actual physical keyboard? External? Built-in English / Spanish version?

I'm using ventura 13.5 (22G74) and the keyboard is this one:
![image](https://github.com/neosergio/Latam-Keyboard/assets/31494271/2fd8dc84-10c2-4c26-aae9-2b4b503cd42b)

**Comment by VolodyaCO** [comment]
> After some search about possible issues, I found this: https://techcommunity.microsoft.com/t5/discussions/zoom-not-working-with-cmd-on-m1-mac/m-p/3055943, so it's possibly related to Chrome specifically @mig8447. @VolodyaCO I tried Safari and it is working properly.

@neosergio I also wasn't able to do cmd + + inside a terminal, I have to use the num block keys
